config/routes.rb
Rails.application.routes.draw do
  root "orders#index"
  get 'transactions/create'
  get 'products/index'
  get 'products/create'
  resources :admin_dash do
    collection {
      post :add_dist
      delete "/remove_dist/:id", :to => 'admin_dash#remove_dist'
    }
  end
  resources :orders do
    resources :transactions
  end
  resources :dist_floats do
    collection { post :admin_float }
  end
  resources :products
  devise_for :admins
  devise_for :distributors, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dist_float.rb
class DistFloat < ApplicationRecord
  belongs_to :distributor
end

app/models/distributor.rb
class Distributor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :transactions
  has_many :distributor_floats
  has_many :dist_floats
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :distributor
  has_many :transactions

end

app/models/payment_channel.rb
class PaymentChannel < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :order
end

app/controllers/admin_dash_controller.rb
class AdminDashController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_distributor, only: [:remove_dist]

  def index
    @distributors = Distributor.all
    @transactions = DistFloat.all
    @orders = Order.all
    @products = Product.all
  end

  def add_dist
    @distributor = Distributor.create!(distributor_params)
    redirect_to admin_dash_index_path, notice: "<%= @distributor %> Created!"
  end

  def remove_dist
    @distributor.delete
    redirect_to admin_dash_index_path
  end

  private

  def set_distributor
    @distributor = Distributor.find(params[:id])
  end

  def distributor_params
    params.permit(:dist_name, :dist_contact, :dist_float, :email, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_distributor!

  def index
    @orders = current_distributor.orders
    @payments = current_distributor.dist_floats
    @products = Product.all
  end

  def create
    @order = current_distributor.orders.build(order_params)
    @order.cost = Product.find(params[:product].to_i).cost * order_params[:quantity].to_i
    @order.save
    redirect_to root_url
  end

  private

  def order_params
    params.permit(:quantity, :pick_up)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def create
    Product.create!(product_params)
    redirect_to admin_dash_index_path
  end

  private

  def product_params
    params.permit(:name, :cost)
  end

end

app/helpers/admin_dash_helper.rb
module AdminDashHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dist_floats_helper.rb
module DistFloatsHelper
end

app/helpers/distributor_floats_helper.rb
module DistributorFloatsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Savanna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="row">
      <div class="col s2 side-nav fixed">
        <ul class="">
          <div class="logo">
            <%= image_tag 'savana', width: 200 %>
            <% if admin_signed_in? %>
              <h3>Admin Dashboard</h3>
            <% elsif distributor_signed_in? %>
              <h3>Distributor Portal</h3>
              <h5>Welcome <%= current_distributor.dist_name %></h5>
              <p><%= link_to "Sign Out", destroy_distributor_session_path, method: "DELETE", class: "btn red" %></p>
            <% end %>
          </div>
        </ul>
      </div>
      <div class="col s10">
          <%= yield %>
      </div>
    </div>

  </body>
</html>